### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [SeaWahl/bwui-capstone-placeholder#5]
Grade: Exceeds Expectations

Summary:
Christine, congrats on finishing your capstone project! You did an excellent job overall; for example, your site was responsive as it adapted to every screen width that I tested it in. You added semantic meaning throughout your project by using the appropriate elements and using roles and labels to supplement compatibility with older browsers. Visually you also did a great job as your color scheme was appropriate, your hover effects added feedback, and the error page you added was a nice touch!

To expand your project a little more consider researching [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables). They're a great tool that allows you to increase the manageability and readability of your stylesheet.

**Comment by SeaWahl** [comment]
Hi Jim, 
Thanks for the review! Appreciate you taking the time to sift through my code. I'll check out the variables tool you mention.

I've also seen CSS snippets where they use something like:   $text-color: #3d3d3d;
and then refer to it later in like:   a { color: $text-color; }

Is that another form of variables?

**Comment by jim-rosales** [comment]
Hi Christine,

It is but those variables are for Sass, or Syntactically Awesome StyleSheets, an extension language for CSS.

Here is a [lesson](https://www.codecademy.com/courses/learn-sass/lessons/hello-sass/exercises/variables?action=resume_content_item) on Sass if you want to learn about them.


The original link I provided on variables work in the exact same way as variables in Sass they only difference is that you can use them without the need to compile (convert) Sass into CSS.

Here is an example variables in plain CSS:
```CSS
:root { /**Example of declaring a variable in the root pseudo-class. **/
  --main-bg-color: brown;
}

/** Using the variable **/
.one {
  color: white;
  background-color: var(--main-bg-color);
  margin: 10px;
  width: 50px;
  height: 50px;
  display: inline-block;
}
```

Let me know if you still have any other questions!
